
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: sites.access.secure-access-cloud.symantec.com
spec:
  group: access.secure-access-cloud.symantec.com
  names:
    kind: Site
    listKind: SiteList
    plural: sites
    singular: site
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: Site is the Schema for the sites API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: SiteSpec defines the desired state of Site
            properties:
              connectors_namespace:
                type: string
              endpoint_url:
                type: string
              number_of_connectors:
                type: integer
              tenant_identifier:
                description: Name is an example field of Site. Edit site_types.go
                  to remove/update
                type: string
            required:
            - connectors_namespace
            - endpoint_url
            - number_of_connectors
            - tenant_identifier
            type: object
          status:
            description: SiteStatus defines the observed state of Site
            properties:
              healthy_connectors:
                additionalProperties:
                  type: string
                type: object
              id:
                description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                  of cluster Important: Run "make" to regenerate code after modifying
                  this file'
                type: string
              number_of_healthy_connectors:
                type: integer
              selector:
                type: string
              un_healthy_connectors:
                additionalProperties:
                  type: string
                type: object
            required:
            - healthy_connectors
            - id
            - number_of_healthy_connectors
            - selector
            - un_healthy_connectors
            type: object
        type: object
    served: true
    storage: true
    subresources:
      scale:
        labelSelectorPath: .status.selector
        specReplicasPath: .spec.number_of_connectors
        statusReplicasPath: .status.NumberOfHealthyConnectors
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
